; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
platform = espressif8266
board = d1_mini
; upload_protocol = espota
; upload_port = 192.168.178.201
upload_port = COM1
monitor_port = COM1
monitor_speed = 115200
lib_deps =
  thomasfredericks/Bounce2@^2.71
  milesburton/DallasTemperature@^3.11.0
  ayushsharma82/ElegantOTA@^3.1.0
  paulstoffregen/OneWire@^2.3.8
  olikraus/U8g2@^2.35.9
build_flags =
  -Wall
build_unflags =
  -w

[env:esp8266_d1mini]
lib_deps =
  ${env.lib_deps}
build_flags =
  ${env.build_flags}
  -DTARGET_ESP8266

[env:esp8266_d1mini_debug]
lib_deps =
  ${env:esp8266_d1mini.lib_deps}
build_flags =
  ${env:esp8266_d1mini.build_flags}
  -DDEBUG_RK
